import os

DEBUG = True
MAIL_SERVER = os.environ['POSTFIX_PORT_587_TCP_ADDR']
MAIL_PORT = 587
MAIL_USE_TLS = True
MAIL_USE_SSL = False
MAIL_USERNAME = 'user'
MAIL_PASSWORD = 'pwd'
MAIL_DEFAULT_SENDER = 'from@example.com'
DB_HOST = os.environ['MONGO_PORT_27017_TCP_ADDR']
DB_PORT = 27017
KEY = 'secret'
ACTIVATION_EXPIRE_DAYS = 5
TOKEN_EXPIRE_HOURS = 1

