DEBUG = False
MAIL_SERVER = '127.0.0.1'
MAIL_PORT = 25
MAIL_USE_TLS = False
MAIL_USE_SSL = False
MAIL_USERNAME = 'user'
MAIL_PASSWORD = 'pwd'
MAIL_DEFAULT_SENDER = 'from@example.com'
DB_HOST = '127.0.0.1'
DB_PORT = 27017
KEY = 'secret'
ACTIVATION_EXPIRE_DAYS = 5
TOKEN_EXPIRE_HOURS = 1

